### ISSUE TITLE
Input Ideas

### ISSUE THREAD

**Issue by e36** [e36/subreddit_backup#2]
Currently the script takes a "hardcoded" thread ID as the input, and it can only be changed by modifying the script file itself.  While that works it has several drawbacks:
    - The script has to be modified in order for a different thread to be worked
    - The script can't be run quickly, nor would the user have any idea which thread is being worked unless they looked at the source code
    - There is no functionality for working multiple threads

I'm not sure if we need the ability to work sets of threads (though it would be useful from a mass-backup perspective), but I do think that selecting the target thread should be broken out into a command line switch.  Argparse would be useful here, as it would allow for something like the following:

subreddit_backup.py -thread_id cx2yf2

The advantage to this is that the script can be reused easily and quickly, and without the fear of someone messing something else up while they're changing the thread ID in the source.  It would also allow us to easily add additional functionality, like logging, target directories, overriding the default json file naming scheme, or specifying files with sets of thread IDs.

**Comment by Mikecom32** [comment]
I'm thinking we will probably need to build in a method to pull all the thread_id's directly from the subreddit, but we could have it parse an input file of thread_ids as well (and programmatically generate said IDs from another script when when needed).

**Resuming**
- Do we want to be able to resume in the event of a failure/disconnection
- If so, do we want to keep track of this in a separate place, or just have it parse the existing thread_ids?

**Incremental backups**
- Is this worth coding?  It could possibly share a lot of the resuming codebase, so it might not be much more work.  If we want to continue archiving things going forward, this is probably good to have.

On a side note, do we want to use a configuration file, command line arguments, or both for passing parameters/configuration?

**Comment by e36** [comment]
Are you talking about just doing a dump of all posts in the subreddit?  I think we can use praw to get that information, but I haven't really done much with it as of yet.  Maybe we should include some kind of "nuclear option" --pull_all switch that will go through everything?  Being able to give specific thread IDs wouldn't be hard at all, and I'm already looking into it using argparse. 

**Resuming**
I think our options here are to either figure out how to identify a failure, pause it, and then resume at a later time; or simply dump the information to a log file so that whomever is running it can look at it after a batch has run.  It's definitely worth investigating, though.

**Incremental Backups**
I also think that this wouldn't be a bad thing to have.  It's probably as easy as just working a thread, comparing it to what is already stored in the database or JSON file, and adding any missing data to the chosen comment chains.

**Arguments**
So this is where I'm a little torn.  Command line arguments (argparse) are probable easier to set up, and quicker for shorter commands, but config files (configparser) would be better if we anticipate more complex operations.  Perhaps for now going the command line route would be the cheapest in terms of effort, and then if things get more sophisticated we can switch over to configs or some combinations of both?
