### ISSUE TITLE
Getting post information

### ISSUE THREAD

**Issue by e36** [e36/subreddit_backup#9]
I'm having trouble figuring out how to get a list of all posts for a subreddit.  PRAW does not appear to have any one way to do that, and the existing methods like get_{top/new/controversial}_by_all are limited to 1,000 posts.

**Comment by Mikecom32** [comment]
I just confirmed with deimorz, reddit actually doesn't have this available in any form.  The site doesn't generate data past item 1000.

The items are available via search, but not "indexed" for any of the views.

We can poll hot/new/top/controversial, pull the uniques, and then we're out of luck from there.  Going forward, we can stay on top of it, but the past data isn't easily available.

We _might_ be able to do some hack-y stuff with searching and timestamp constraints, but we'll need to test it.

**Comment by e36** [comment]
Thanks for checking.  I think that other script that you told me about does some weird timestamp stuff, so I need to dig into that to see if it works.  

I was thinking about polling everything like you suggested, and including some kind of functionality to retrieve specific thread IDs.
